/** Client-held signatures. No private key is accepted or generated by this verifier. */
import { createHash, createPublicKey, verify } from 'node:crypto';
import { verifyMessage } from 'ethers';
import { base58btc } from 'multiformats/bases/base58';
import { verifyAuthenticationResponse } from '@simplewebauthn/server';
import { decodeCredentialPublicKey } from '@simplewebauthn/server/helpers';
import type { ResourceSigningKey } from '../../deploy/mcp-relay/resource-compositions.js';

export type ClientSigningKey = ResourceSigningKey;
export interface ClientSignature {
  readonly schema: 'interego.client-signature/v1';
  readonly key: ClientSigningKey;
  readonly message: string;
  readonly signature?: string;
  readonly assertion?: Record<string, unknown>;
}
export interface VerifiedClientAuthorization {
  readonly keyId: string;
  readonly scheme: ClientSigningKey['scheme'];
  readonly proof: ClientSignature;
}
const verified = new WeakSet<object>();
const digest = (value: string | Uint8Array): string => createHash('sha256').update(value).digest('hex');
const b64 = (value: Uint8Array): string => Buffer.from(value).toString('base64url');

function ed25519Bytes(value: string): Uint8Array {
  const bytes = base58btc.decode(value);
  if (bytes.length !== 34 || bytes[0] !== 0xed || bytes[1] !== 0x01) throw new Error('expected an Ed25519 multicodec public key');
  return bytes.slice(2);
}

/** Fingerprint key material, never a credential label or the caller's chosen DID. */
export function clientKeyId(key: ClientSigningKey): string {
  if (key.scheme === 'eip191') {
    if (!/^0x[0-9a-fA-F]{40}$/.test(key.address ?? '')) throw new Error('invalid signing wallet');
    return `did:ethr:${key.address!.toLowerCase()}`;
  }
  if (key.scheme === 'ed25519') return 'did:key:' + base58btc.encode(new Uint8Array([0xed, 0x01, ...ed25519Bytes(key.publicKeyMultibase ?? '')]));
  if (key.scheme !== 'webauthn' || !key.publicKey) throw new Error('unsupported signing key');
  const cose = decodeCredentialPublicKey(Buffer.from(key.publicKey, 'base64url')) as Map<number, unknown>;
  // Strip COSE metadata and map ordering. Two credentials over the same public key
  // must count as ONE key, even when their IDs or encodings differ.
  const kty = cose.get(1);
  if (kty === 1 && cose.get(-1) === 6 && cose.get(-2) instanceof Uint8Array) {
    return 'did:key:' + base58btc.encode(new Uint8Array([0xed, 0x01, ...cose.get(-2) as Uint8Array]));
  }
  const parameter = (n: number): string | number => {
    const value = cose.get(n);
    if (typeof value === 'number') return value;
    if (value instanceof Uint8Array) {
      // RSA n/e are unsigned integers. Redundant zero octets do not make a new
      // public key, even when a COSE/JWK decoder accepts both representations.
      if (kty === 3) {
        let first = 0;
        while (first < value.length - 1 && value[first] === 0) first++;
        return b64(value.slice(first));
      }
      return b64(value);
    }
    throw new Error('malformed COSE public key');
  };
  const material = kty === 2 ? [kty, parameter(-1), parameter(-2), parameter(-3)]
    : kty === 1 || kty === 3 ? [kty, parameter(-1), parameter(-2)] : null;
  if (!material) throw new Error('unsupported COSE key type');
  return 'urn:sha256:' + digest(JSON.stringify(material));
}

export function clientSigningMessage(message: string, key: ClientSigningKey): string {
  return `Interego client authorization v1\nKey: ${clientKeyId(key)}\n${message}`;
}

function freeze<T>(value: T): T {
  if (value && typeof value === 'object') {
    for (const child of Object.values(value)) freeze(child);
    Object.freeze(value);
  }
  return value;
}

/**
 * With allowedKeys, admission additionally requires a current registered credential.
 * Replay verifies the retained signature against its admitted public-key snapshot.
 * Identity binding is supplied by the identity service; the signature itself is
 * made by the client. Neither a bearer nor a relay signature satisfies this check.
 */
export async function verifyClientAuthorization(
  raw: unknown, expectedMessage: string, allowedKeys?: readonly ClientSigningKey[],
): Promise<VerifiedClientAuthorization> {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('client signature is required');
  const supplied = raw as ClientSignature;
  if (Object.keys(supplied).some(key => !['schema', 'key', 'message', 'signature', 'assertion'].includes(key))) throw new Error('unknown client signature field');
  if (supplied.schema !== 'interego.client-signature/v1' || supplied.message !== expectedMessage || !supplied.key) {
    throw new Error('client signature does not bind the exact action receipt');
  }
  const id = clientKeyId(supplied.key);
  const registered = allowedKeys?.find(key => clientKeyId(key) === id
    && key.scheme === supplied.key.scheme
    && (key.scheme !== 'webauthn' || key.credentialId === supplied.key.credentialId));
  if (allowedKeys && !registered) throw new Error('signing key is not a registered credential of the authenticated actor');
  // Never use caller-supplied RP/origin restrictions at admission.
  const key = registered ?? supplied.key;
  const message = clientSigningMessage(expectedMessage, key);
  if (key.scheme === 'eip191') {
    if (typeof supplied.signature !== 'string' || verifyMessage(message, supplied.signature).toLowerCase() !== key.address!.toLowerCase()) {
      throw new Error('client wallet signature is invalid');
    }
  } else if (key.scheme === 'ed25519') {
    const publicKey = createPublicKey({
      key: Buffer.concat([Buffer.from('302a300506032b6570032100', 'hex'), Buffer.from(ed25519Bytes(key.publicKeyMultibase!))]),
      format: 'der', type: 'spki',
    });
    if (typeof supplied.signature !== 'string'
      || !verify(null, Buffer.from(message), publicKey, Buffer.from(supplied.signature, 'base64url'))) {
      throw new Error('client Ed25519 signature is invalid');
    }
  } else {
    if (!key.credentialId || !key.origins?.length || !key.rpIds?.length || !supplied.assertion) throw new Error('passkey verification context is incomplete');
    if (supplied.assertion['id'] !== key.credentialId) throw new Error('passkey assertion names a different credential');
    const response = supplied.assertion['response'] as Record<string, unknown> | undefined;
    const clientData = JSON.parse(Buffer.from(String(response?.['clientDataJSON'] ?? ''), 'base64url').toString('utf8')) as Record<string, unknown>;
    if (clientData['crossOrigin'] === true || clientData['topOrigin'] !== undefined) throw new Error('cross-origin client signing is not permitted');
    const result = await verifyAuthenticationResponse({
      response: supplied.assertion as unknown as Parameters<typeof verifyAuthenticationResponse>[0]['response'],
      expectedChallenge: Buffer.from(digest(message), 'hex').toString('base64url'),
      expectedOrigin: [...key.origins], expectedRPID: [...key.rpIds], requireUserVerification: true,
      credential: { id: key.credentialId, publicKey: Buffer.from(key.publicKey!, 'base64url'), counter: 0 },
    });
    if (!result.verified) throw new Error('client passkey signature is invalid');
    // A signature here is scoped to an exact CAS predecessor, action, contract,
    // actor and timestamp. It is never accepted as a reusable login assertion.
  }
  const proof = JSON.parse(JSON.stringify({ ...supplied, key })) as ClientSignature;
  const result = freeze({ keyId: id, scheme: key.scheme, proof });
  // Cryptographic replay alone must not mint a live-admission capability.
  if (allowedKeys !== undefined) verified.add(result);
  return result;
}

export function requireVerifiedClientAuthorization(value: VerifiedClientAuthorization | undefined, message: string): VerifiedClientAuthorization {
  if (!value || !verified.has(value) || value.proof.message !== message) throw new Error('independently verified client signature is required');
  return value;
}
