"""The I2IDL-X semantic layer, as data.

Two questions, kept apart on purpose:

  1. What is an I2IDL concept?  A term: an information content entity (IAO, CCO), a concept (DOLCE-UltraLite),
     a knowledge concept (gist), a defined term (schema.org). Its definitions, evidence, sources, collections and
     scheme are information entities too. These are "record" alignments.

  2. What does an I2IDL concept classify?  The things in the world it names. "Learning Record Store" the concept
     is a term; an organization's LRS deployment is software. Each concept gets one *referent category*
     (CATEGORIES below), and each category is aligned, once and with a rationale, to the upper ontologies and
     peer vocabularies. Data that says `ex:x i2x:isClassifiedBy i2idl:c` is then typed in every one of them.

Everything here is I2IDL-X's interpretation, published Hypothetical in i2idlx-alignments; nothing changes I2IDL's
record. Terms are CURIEs over PREFIXES; build.py refuses any term that is not in the snapshot of its vocabulary
(evidence/upper/, evidence/peer-terms.json, or the Interego and Foxxi namespace files in evidence/).
"""

PREFIXES = {
    "obo": "http://purl.obolibrary.org/obo/",
    "cco": "https://www.commoncoreontologies.org/",
    "gist": "https://w3id.org/semanticarts/ns/ontology/gist/",
    "dul": "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#",
    "gufo": "http://purl.org/nemo/gufo#",
    "prov": "http://www.w3.org/ns/prov#",
    "schema": "https://schema.org/",
    "org": "http://www.w3.org/ns/org#",
    "dct": "http://purl.org/dc/terms/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "lrmi": "http://purl.org/dcx/lrmi-terms/",
    "asn": "http://purl.org/ASN/schema/core/",
    "esco": "http://data.europa.eu/esco/model#",
    "elm": "http://data.europa.eu/snb/model/elm/",
    "ceterms": "https://purl.org/ctdl/terms/",
    "ceasn": "https://purl.org/ctdlasn/terms/",
    "ob3": "https://purl.imsglobal.org/spec/vc/ob/vocab.html#",
    "case": "https://purl.imsglobal.org/spec/case/v1p0/vocab#",
    "cred": "https://www.w3.org/2018/credentials#",
    "xapi": "https://w3id.org/xapi/ontology#",
    "xprof": "https://w3id.org/xapi/profiles/ontology#",
    "ler": "https://foxxi-bridge.interego.xwisee.com/ns/ieee-ler#",
    "tla": "https://foxxi-bridge.interego.xwisee.com/ns/adl-tla#",
    "iep": "https://markjspivey-xwisee.github.io/interego/ns/iep#",
    "ie": "https://markjspivey-xwisee.github.io/interego/ns/interego#",
    "ieh": "https://markjspivey-xwisee.github.io/interego/ns/harness#",
    "hyprcat": "https://markjspivey-xwisee.github.io/interego/ns/hyprcat#",
    "hypragent": "https://markjspivey-xwisee.github.io/interego/ns/hypragent#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "gs": "https://glossarystudio.app/ns/",
}

# Vocabularies, in the order the reference page and the workbench show them. "kind": upper | peer | interego | foxxi.
# "columns" groups vocabularies into the columns of the alignment matrix.
VOCABS = [
    {"prefix": "obo", "column": "bfo", "kind": "upper", "title": "BFO 2020 (ISO/IEC 21838-2) with IAO",
     "short": "BFO · IAO", "home": "https://basic-formal-ontology.org/"},
    {"prefix": "cco", "column": "cco", "kind": "upper", "title": "Common Core Ontologies (CCO 2), on BFO 2020",
     "short": "CCO", "home": "https://github.com/CommonCoreOntology/CommonCoreOntologies"},
    {"prefix": "gist", "column": "gist", "kind": "upper", "title": "gist 14.1 (Semantic Arts)",
     "short": "gist", "home": "https://www.semanticarts.com/gist/"},
    {"prefix": "dul", "column": "dul", "kind": "upper", "title": "DOLCE+DnS Ultralite (DUL)",
     "short": "DUL", "home": "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl"},
    {"prefix": "gufo", "column": "gufo", "kind": "upper", "title": "gUFO 1.0 (Unified Foundational Ontology)",
     "short": "gUFO", "home": "https://nemo-ufes.github.io/gufo/"},
    {"prefix": "prov", "column": "prov", "kind": "upper", "title": "PROV-O (W3C)", "short": "PROV-O",
     "home": "https://www.w3.org/TR/prov-o/"},
    {"prefix": "schema", "column": "schema", "kind": "upper", "title": "schema.org 30.1", "short": "schema.org",
     "home": "https://schema.org/"},
    {"prefix": "org", "column": "schema", "kind": "upper", "title": "W3C Organization Ontology", "short": "ORG",
     "home": "https://www.w3.org/TR/vocab-org/"},
    {"prefix": "dct", "column": "schema", "kind": "upper", "title": "DCMI Metadata Terms", "short": "DCMI",
     "home": "https://www.dublincore.org/specifications/dublin-core/dcmi-terms/"},
    {"prefix": "lrmi", "column": "peer", "kind": "peer", "title": "LRMI (DCMI Learning Resource Metadata Initiative)",
     "short": "LRMI", "home": "https://www.dublincore.org/specifications/lrmi/"},
    {"prefix": "ceterms", "column": "peer", "kind": "peer", "title": "CTDL (Credential Engine)", "short": "CTDL",
     "home": "https://credreg.net/ctdl/terms"},
    {"prefix": "ceasn", "column": "peer", "kind": "peer", "title": "CTDL-ASN (Credential Engine)", "short": "CTDL-ASN",
     "home": "https://credreg.net/ctdlasn/terms"},
    {"prefix": "esco", "column": "peer", "kind": "peer", "title": "ESCO model (European Commission)", "short": "ESCO",
     "home": "https://esco.ec.europa.eu/"},
    {"prefix": "elm", "column": "peer", "kind": "peer", "title": "European Learning Model 3 (Europass)", "short": "ELM",
     "home": "http://data.europa.eu/snb/model/elm"},
    {"prefix": "asn", "column": "peer", "kind": "peer", "title": "Achievement Standards Network (ASN)", "short": "ASN",
     "home": "http://purl.org/ASN/schema/core/"},
    {"prefix": "ob3", "column": "peer", "kind": "peer", "title": "Open Badges 3.0 (1EdTech)", "short": "Open Badges",
     "home": "https://www.imsglobal.org/spec/ob/v3p0/"},
    {"prefix": "case", "column": "peer", "kind": "peer", "title": "CASE 1.0 (1EdTech)", "short": "CASE",
     "home": "https://www.imsglobal.org/activity/case"},
    {"prefix": "xapi", "column": "peer", "kind": "peer", "title": "xAPI ontology (ADL)", "short": "xAPI",
     "home": "https://w3id.org/xapi/ontology"},
    {"prefix": "xprof", "column": "peer", "kind": "peer", "title": "xAPI Profiles ontology (ADL)", "short": "xAPI Profiles",
     "home": "https://w3id.org/xapi/profiles/ontology"},
    {"prefix": "cred", "column": "peer", "kind": "peer", "title": "W3C Verifiable Credentials", "short": "W3C VC",
     "home": "https://www.w3.org/TR/vc-data-model/"},
    {"prefix": "ler", "column": "foxxi", "kind": "foxxi", "title": "IEEE LER vocabulary (Foxxi bridge)", "short": "IEEE LER",
     "home": "https://foxxi-bridge.interego.xwisee.com/ns/ieee-ler"},
    {"prefix": "tla", "column": "foxxi", "kind": "foxxi", "title": "ADL TLA vocabulary (Foxxi bridge)", "short": "ADL TLA",
     "home": "https://foxxi-bridge.interego.xwisee.com/ns/adl-tla"},
    {"prefix": "iep", "column": "interego", "kind": "interego", "title": "Interego protocol (iep:)", "short": "iep",
     "home": "https://markjspivey-xwisee.github.io/interego/ns/iep"},
    {"prefix": "ie", "column": "interego", "kind": "interego", "title": "Interego core (ie:)", "short": "ie",
     "home": "https://markjspivey-xwisee.github.io/interego/ns/interego"},
    {"prefix": "ieh", "column": "interego", "kind": "interego", "title": "Interego harness (ieh:)", "short": "ieh",
     "home": "https://markjspivey-xwisee.github.io/interego/ns/harness"},
    {"prefix": "hyprcat", "column": "interego", "kind": "interego", "title": "HyprCat", "short": "HyprCat",
     "home": "https://markjspivey-xwisee.github.io/interego/ns/hyprcat"},
    {"prefix": "hypragent", "column": "interego", "kind": "interego", "title": "HyprAgent", "short": "HyprAgent",
     "home": "https://markjspivey-xwisee.github.io/interego/ns/hypragent"},
]

# Columns of the alignment matrix (upper ontologies first, then peers).
COLUMNS = [("bfo", "BFO · IAO"), ("cco", "CCO"), ("gist", "gist"), ("dul", "DUL"), ("gufo", "gUFO"),
           ("prov", "PROV-O"), ("schema", "schema.org · ORG · DCMI"), ("peer", "Peer vocabularies")]

# ── Referent categories ───────────────────────────────────────────────────────────────────────────────
# referent: classes every classified thing joins (rdfs:subClassOf from the category class).
# concept:  classes the *concept itself* joins when its referent category is this one (DUL concept kinds, gist
#           category kinds).
# expressible: peer classes a description of this kind of thing is published as (annotation only, no typing).
# Sub-categories inherit their parent's alignments in OWL, so a child lists only what it adds.
CATEGORIES = [
    # Occurrents
    {"id": "process", "cls": "ProcessReferent", "label": "Process or event",
     "definition": "Something that happens or unfolds in time — a process, event or episode — whether or not anyone intends it.",
     "group": "Things that happen",
     "referent": ["obo:BFO_0000015", "gist:Event", "dul:Event", "gufo:Event", "prov:Activity"],
     "concept": ["dul:EventType", "gist:Behavior"],
     "why": "Occurrents in every upper ontology: BFO process, gist and DUL Event, gUFO Event; PROV-O Activity is 'something that occurs over a period of time'. The concept that names such a process is a DUL EventType and a gist Behavior ('a category indicating the nature of an activity')."},
    {"id": "activity", "cls": "ActivityReferent", "label": "Activity or practice", "broader": "process",
     "definition": "An intentional activity agents carry out: a practice, procedure or piece of work in teaching, design, research, data work or governance.",
     "group": "Things that happen",
     "referent": ["cco:ont00000005", "dul:Action", "schema:Action"],
     "concept": ["dul:Task"],
     "why": "An act in which agents play a causative role: CCO Act, DUL Action (an event with a participating agent executing a task), schema.org Action. The concept is a DUL Task, the EventType that classifies actions."},
    {"id": "learning", "cls": "LearningActivityReferent", "label": "Learning activity", "broader": "activity",
     "definition": "An activity in which someone learns, studies, practises or is taught.",
     "group": "Things that happen",
     "referent": [],
     "expressible": ["elm:LearningActivitySpecification"],
     "why": "Inherits the activity alignments. CCO's educational acts require an educational organization or an imparting agent, which self-directed and experiential learning lack, so only teaching gets a CCO class (below). ELM publishes descriptions of such activities as LearningActivitySpecification."},
    {"id": "teaching", "cls": "TeachingActivityReferent", "label": "Teaching or training activity", "broader": "learning",
     "definition": "A learning activity in which knowledge, skill or values are imparted by one or more people to others.",
     "group": "Things that happen",
     "referent": ["cco:ont00000234"],
     "why": "CCO Act of Training: 'a Planned Act in which knowledge, skills or values are imparted from one or more Agents to at least one other Agent'."},
    {"id": "assessment", "cls": "AssessmentReferent", "label": "Assessment, evaluation or test", "broader": "activity",
     "definition": "An activity whose aim is to determine a result about knowledge, skill, quality or impact: assessments, evaluations, tests and validations.",
     "group": "Things that happen",
     "referent": ["cco:ont00000636", "gist:Determination"],
     "expressible": ["ceterms:AssessmentProfile", "elm:LearningAssessmentSpecification"],
     "why": "CCO Act of Appraisal ('evaluating, assessing, estimating, or judging the nature, value, importance, condition, or quality of something or someone'); gist Determination ('an event whose purpose is to establish a specific result ... by research, measuring, evaluating'). CTDL and ELM publish descriptions of assessments as AssessmentProfile and LearningAssessmentSpecification."},
    # Plans and information
    {"id": "plan", "cls": "PlanReferent", "label": "Plan or method", "abstract": True,
     "definition": "A specification of what is to be done — a method, technique, course or programme — independent of any one occasion of doing it.",
     "group": "Information and plans",
     "referent": ["obo:BFO_0000031", "obo:IAO_0000104", "cco:ont00000974", "dul:Description", "prov:Plan"],
     "why": "A plan specification in BFO/IAO (a directive information entity, generically dependent), a CCO Plan ('prescribes some set of intended Intentional Acts'), a DUL Description and a PROV Plan. Doing it is an activity that realizes the plan, not the plan itself."},
    {"id": "method", "cls": "MethodReferent", "label": "Method, technique or approach", "broader": "plan",
     "definition": "A reusable way of doing something — a technique, strategy or approach.",
     "group": "Information and plans",
     "referent": ["gist:TaskTemplate", "dul:Method"],
     "why": "gist TaskTemplate ('an outline of a task of a particular type, which is the basis for executing such tasks'); DUL Method ('a Description that defines or uses concepts in order to guide carrying out actions')."},
    {"id": "program", "cls": "ProgramReferent", "label": "Course, programme or curriculum", "broader": "plan",
     "definition": "A structured offering or plan of learning: a course, programme or curriculum.",
     "group": "Information and plans",
     "referent": ["dul:Plan", "gist:Specification", "schema:Course", "ceterms:LearningOpportunity", "elm:LearningOpportunity"],
     "expressible": ["ceterms:Course", "ceterms:LearningProgram", "elm:LearningActivitySpecification"],
     "why": "A plan with an explicit goal (DUL Plan) that specifies a learning offering (gist Specification). schema.org Course is 'a description of an educational course which may be offered as distinct instances'; CTDL and ELM type the opportunity itself as LearningOpportunity."},
    {"id": "information", "cls": "InformationReferent", "label": "Information artifact",
     "definition": "Information content — a document, representation or record — independent of the medium that carries it.",
     "group": "Information and plans",
     "referent": ["obo:BFO_0000031", "obo:IAO_0000030", "cco:ont00000958", "gist:Content", "dul:InformationObject",
                  "gufo:Object", "prov:Entity", "schema:CreativeWork"],
     "why": "An information content entity in IAO and CCO (generically dependent on its carriers), gist Content ('information available in some medium'), a DUL InformationObject, a gUFO object (gUFO counts socially defined artifacts such as a constitution as objects), a PROV entity and a schema.org CreativeWork."},
    {"id": "specification", "cls": "SpecificationReferent", "label": "Standard or specification", "broader": "information",
     "definition": "A normative document or set of rules that says how something must be done or structured: standards, specifications, profiles and templates.",
     "group": "Information and plans",
     "referent": ["obo:IAO_0000033", "cco:ont00000965", "gist:Specification", "dct:Standard"],
     "why": "Prescriptive information: IAO directive information entity, CCO Prescriptive ICE, gist Specification ('sufficiently precise to allow evaluating conformance'), DCMI Standard ('a reference point against which other things can be evaluated or compared')."},
    {"id": "format", "cls": "FormatReferent", "label": "Data format, language or identifier scheme", "broader": "specification",
     "definition": "A format, language or identifier scheme that prescribes how data is written or exchanged. It classifies formats, not files written in them (use dct:format for those).",
     "group": "Information and plans",
     "referent": ["obo:IAO_0000098", "cco:ont00001175", "gist:Language"],
     "why": "IAO data format specification, CCO Language ('prescribes a canonical format for communication'), gist Language ('a recognized, organized set of symbols and grammar')."},
    {"id": "data", "cls": "DataReferent", "label": "Data or record", "broader": "information",
     "definition": "Recorded data: records, datasets, data structures and the values they hold.",
     "group": "Information and plans",
     "referent": ["obo:IAO_0000027", "cco:ont00000853"],
     "why": "IAO data entity ('intended to be one or more truthful statements about something') and CCO Descriptive ICE ('describes some Entity'). xAPI's own ontology models Statement, Agent and Result as statement parts, which agrees with I2IDL defining them as data structures."},
    {"id": "credential", "cls": "CredentialReferent", "label": "Credential or record of achievement", "broader": "information",
     "definition": "A credential that attests to what someone has learned or can do: badges, certificates, micro-credentials, verifiable records.",
     "group": "Information and plans",
     "referent": ["obo:IAO_0000310", "cco:ont00002002", "schema:EducationalOccupationalCredential"],
     "expressible": ["ceterms:Credential", "ob3:Achievement", "esco:Qualification", "elm:Qualification"],
     "why": "An IAO document and a CCO Certificate ('attests to certain demonstrated characteristics of an Object, Person, or Organization'); schema.org EducationalOccupationalCredential. CTDL Credential, Open Badges Achievement and ESCO/ELM Qualification describe the credential type rather than one issued credential, so they are offered for publishing, not used for typing."},
    {"id": "resource", "cls": "LearningResourceReferent", "label": "Learning resource", "broader": "information",
     "definition": "Content or material used for learning or teaching: digital learning materials, open educational resources, worked examples, simulations.",
     "group": "Information and plans",
     "referent": ["schema:LearningResource", "lrmi:LearningResource", "asn:LearningResource"],
     "why": "The learning-resource classes of schema.org, LRMI ('a persistent resource ... that explicitly involves, specifies or entails a learning activity') and ASN."},
    {"id": "model", "cls": "ModelReferent", "label": "Model, framework or theory",
     "definition": "A conceptual model, framework, theory or law that describes or explains how something is or works.",
     "group": "Information and plans",
     "referent": ["obo:BFO_0000031", "obo:IAO_0000030", "cco:ont00000853", "gist:KnowledgeConcept", "dul:Description",
                  "prov:Entity", "schema:CreativeWork"],
     "why": "Descriptive information (IAO ICE, CCO Descriptive ICE); a gist KnowledgeConcept ('an abstract concept that arises from the distillation of experience ... it has rich structure'); a DUL Description (a conceptualization), kept apart from the information objects that express it."},
    {"id": "norm", "cls": "NormReferent", "label": "Policy, principle or norm",
     "definition": "A policy, principle, right or obligation that guides or constrains what people and systems should do.",
     "group": "Information and plans",
     "referent": ["obo:BFO_0000031", "obo:IAO_0000033", "cco:ont00000965", "gist:Requirement", "dul:Norm", "prov:Entity"],
     "why": "Prescriptive information (IAO directive information entity, CCO Prescriptive ICE); gist Requirement ('the obligation of a person or organization to behave in a certain way'); DUL Norm."},
    # Agents and groups
    {"id": "agent", "cls": "AgentReferent", "label": "Agent in a role",
     "definition": "A person, organization or software agent playing the role a concept names.",
     "group": "Agents and groups",
     "referent": ["dul:Agent", "prov:Agent"],
     "concept": ["dul:Role"],
     "why": "Role players are agents in DUL and PROV-O. The concept itself is a DUL Role ('a Concept that classifies an Object'). No BFO class: some of these roles are played by software, which BFO does not count as a material agent."},
    {"id": "person", "cls": "PersonReferent", "label": "Person in a role or occupation", "broader": "agent",
     "definition": "A person playing the role or holding the occupation a concept names.",
     "group": "Agents and groups",
     "referent": ["obo:BFO_0000030", "cco:ont00001262", "gist:Person", "dul:Person", "gufo:Object", "prov:Person", "schema:Person"],
     "bearsRole": True,
     "expressible": ["ceterms:WorkRole", "ceterms:Occupation", "esco:Occupation", "schema:Occupation"],
     "why": "A BFO object (and CCO Person) that bears the role: the role is a realizable entity inhering in the person, so the person is typed, and the build adds 'bearer of some role' (BFO 2020) for reasoners that use it. Occupational roles are published in CTDL as WorkRole or Occupation and in ESCO and schema.org as Occupation."},
    {"id": "organization", "cls": "OrganizationReferent", "label": "Organization or institution",
     "definition": "An organization, institution, committee or team that acts as a unit.",
     "group": "Agents and groups",
     "referent": ["obo:BFO_0000027", "cco:ont00001180", "gist:Organization", "dul:Organization", "gufo:Object",
                  "prov:Organization", "schema:Organization", "org:Organization"],
     "why": "BFO object aggregate (CCO Organization is a Group of Agents with organization rules); gist, DUL, PROV-O, schema.org and W3C ORG Organization. DUL and PROV-O make organizations agents; the concept that names a kind of organization is not a role, so it is not a DUL Role."},
    {"id": "edorg", "cls": "EducationalOrganizationReferent", "label": "Educational organization", "broader": "organization",
     "definition": "An organization whose primary purpose is education or training.",
     "group": "Agents and groups",
     "referent": ["cco:ont00000564", "schema:EducationalOrganization"],
     "why": "CCO Educational Organization ('primary purpose is to provide training or otherwise facilitate learning'); schema.org EducationalOrganization."},
    {"id": "group", "cls": "GroupReferent", "label": "Group, community or population",
     "definition": "People considered collectively: a community, network, team or population.",
     "group": "Agents and groups",
     "referent": ["obo:BFO_0000027", "cco:ont00000300", "gist:Collection", "dul:Collective", "gufo:Collection"],
     "why": "BFO object aggregate and CCO Group of Agents; gist Collection ('a grouping of things'); DUL Collective ('a Collection whose members are agents'); gUFO Collection. Kept apart from organizations, which act as one agent."},
    # Dependent entities
    {"id": "disposition", "cls": "DispositionReferent", "label": "Capacity or disposition",
     "definition": "A capacity, ability or tendency that a person, group or system has and can exercise.",
     "group": "Characteristics",
     "referent": ["obo:BFO_0000016", "dul:Quality", "gufo:IntrinsicMode"],
     "why": "BFO disposition (realized when its bearer is in the right circumstances); DUL Quality (DUL has no dispositions); gUFO IntrinsicMode, whose own examples include 'Bob's math skills' and 'his belief'."},
    {"id": "competence", "cls": "CompetenceReferent", "label": "Competence, skill or knowledge", "broader": "disposition",
     "definition": "Knowledge, skill or competence that a person has and can apply.",
     "group": "Characteristics",
     "referent": ["cco:ont00001379", "gist:IntellectualProperty"],
     "expressible": ["ceasn:Competency", "case:dtCFItem", "asn:Statement", "esco:Skill", "elm:LearningOutcome",
                     "ler:CompetencyDefinition", "tla:Competency"],
     "why": "CCO Agent Capability ('a Realizable Entity that inheres in a Material Entity in virtue of ... its capacity to realize it in some Planned Act'); gist IntellectualProperty, which 'can also be tacit knowledge, know-how, or skill'. A competency *definition* is information; CTDL-ASN, CASE, ASN, ESCO, ELM, IEEE LER and ADL TLA publish those, so they are offered for publishing."},
    {"id": "attitude", "cls": "AttitudeReferent", "label": "Attitude, belief or mindset", "broader": "disposition",
     "definition": "A belief, attitude, mindset or self-conception held by a person.",
     "group": "Characteristics",
     "referent": [],
     "why": "Mental dispositions: inherits BFO disposition, DUL Quality and gUFO IntrinsicMode."},
    {"id": "quality", "cls": "QualityReferent", "label": "Quality, state or degree",
     "definition": "A characteristic, state or degree of something — how much, how well, how fair — that depends on what it characterizes.",
     "group": "Characteristics",
     "referent": ["obo:BFO_0000020", "gist:Aspect", "dul:Quality", "gufo:Aspect"],
     "why": "Specifically dependent continuants in BFO (BFO only lets these inhere in independent continuants, so 'data quality' is strictly a quality of data's carriers); gist Aspect ('a measurable characteristic'); DUL Quality; gUFO Aspect."},
    {"id": "measure", "cls": "MeasureReferent", "label": "Measure, indicator or benchmark",
     "definition": "A quantity, indicator, benchmark or reference value used to measure or compare.",
     "group": "Characteristics",
     "referent": ["obo:BFO_0000031", "obo:IAO_0000027", "cco:ont00001163", "gist:Magnitude", "dul:SocialObjectAttribute",
                  "gufo:QualityValue", "schema:QuantitativeValue"],
     "concept": ["dul:Parameter"],
     "why": "Recorded measures: IAO data entity and CCO Measurement ICE; gist Magnitude ('the amount of a measurable characteristic'); DUL SocialObjectAttribute ('statistical attributes over a collection of entities'); gUFO QualityValue. The concept is a DUL Parameter, which classifies such regions."},
    {"id": "situation", "cls": "SituationReferent", "label": "Situation, setting or condition",
     "definition": "A setting, environment or state of affairs in which things stand in relations: learning environments, problem spaces, divides, lock-in.",
     "group": "Characteristics",
     "referent": ["dul:Situation", "gufo:Situation"],
     "why": "DUL and gUFO both have Situations (configurations of entities standing in relations). BFO, CCO and gist do not model states of affairs, so they get no class here."},
    # Systems and things
    {"id": "software", "cls": "SoftwareReferent", "label": "Software system or service", "abstract": True,
     "definition": "A software system, service or interface.",
     "group": "Systems and things",
     "referent": ["obo:BFO_0000031", "obo:IAO_0000010", "cco:ont00000965", "gist:System", "dul:InformationObject", "prov:Entity"],
     "why": "IAO software ('a plan specification composed of a series of instructions that can be ... executed by a processing unit'), so generically dependent, with CCO's matching Prescriptive ICE; gist System; DUL treats software as an information object realized by physical agents."},
    {"id": "application", "cls": "ApplicationReferent", "label": "Application or platform", "broader": "software",
     "definition": "A software application or platform people or systems use.",
     "group": "Systems and things",
     "referent": ["obo:IAO_0000594", "schema:SoftwareApplication"],
     "why": "IAO software application and schema.org SoftwareApplication."},
    {"id": "webapi", "cls": "WebApiReferent", "label": "Web API or endpoint", "broader": "software",
     "definition": "A web service interface or endpoint.",
     "group": "Systems and things",
     "referent": ["schema:WebAPI"],
     "why": "schema.org WebAPI ('an application programming interface accessible over Web/Internet technologies')."},
    {"id": "ecosystem", "cls": "EcosystemReferent", "label": "Socio-technical system or ecosystem",
     "definition": "A system of interacting people, organizations, technologies, data and practices that operates as a whole.",
     "group": "Systems and things",
     "referent": ["gist:System", "dul:Situation", "gufo:Situation"],
     "why": "gist System ('a composite made up of interacting or interdependent components that together operate as a whole'). Its parts span continuants and processes, so BFO has no single class for it; DUL and gUFO treat it as a situation."},
    {"id": "technology", "cls": "TechnologyReferent", "label": "Technology (hardware or software)",
     "definition": "A technology, device or technical setup that may be hardware, software or both.",
     "group": "Systems and things",
     "referent": ["obo:BFO_0000002", "dul:Object", "prov:Entity"],
     "why": "Only what holds for both hardware and software: a BFO continuant and a DUL Object."},
    {"id": "material", "cls": "MaterialResourceReferent", "label": "Facility or material resource",
     "definition": "Physical facilities, equipment and material resources.",
     "group": "Systems and things",
     "referent": ["obo:BFO_0000040", "cco:ont00000995", "gist:PhysicalIdentifiableItem", "dul:PhysicalArtifact", "gufo:Object", "prov:Entity"],
     "why": "BFO material entity and CCO Material Artifact; gist PhysicalIdentifiableItem; DUL PhysicalArtifact."},
    # Neither
    {"id": "discipline", "cls": "DisciplineReferent", "label": "Field of study or practice", "mode": "subject",
     "definition": "A discipline or field. These concepts are subjects: link work to them with dct:subject or schema:about. I2IDL-X types nothing from them.",
     "group": "Subjects",
     "referent": [],
     "concept": ["gist:Discipline"],
     "expressible": ["esco:FoETCode"],
     "why": "gist models a discipline as a category ('an area of study or practice'), not as something that has instances; ISCED-F fields of education (ESCO FoET codes) are the peer."},
    {"id": "notion", "cls": "NotionReferent", "label": "No single category", "mode": "none",
     "definition": "A concept whose instances have no single upper-ontology category, such as xAPI's Activity, which may be anything an actor interacts with.",
     "group": "Subjects",
     "referent": [],
     "why": "Typing these would be wrong for some of their instances, so I2IDL-X leaves them untyped."},
]
CAT_BY_ID = {c["id"]: c for c in CATEGORIES}

# ── Which category each concept's referents fall in ────────────────────────────────────────────────────
# I2IDL type collection → default category (the reason is I2IDL's own typing). CONCEPT_CATEGORY overrides it,
# and every override says why, from the concept's own definition.
TYPE_DEFAULT = {
    "practice": "activity", "process": "activity", "evaluation": "assessment", "method": "method",
    "system": "application", "infrastructure": "material", "standard": "specification", "framework": "model",
    "role": "person", "population": "group", "institutional-concept": "edorg", "policy": "norm",
    "principle": "norm", "discipline": "discipline", "field": "discipline",
}
TYPE_DEFAULT_WHY = {
    "practice": "I2IDL types it as a Practice: something people do.",
    "process": "I2IDL types it as a Process.",
    "evaluation": "I2IDL types it as an Evaluation.",
    "method": "I2IDL types it as a Method: a reusable way of doing something.",
    "system": "I2IDL types it as a System, and it is a software system people or services use.",
    "infrastructure": "I2IDL types it as Infrastructure: physical facilities and equipment.",
    "standard": "I2IDL types it as a Standard.",
    "framework": "I2IDL types it as a Framework: a structured reference model.",
    "role": "I2IDL types it as a Role filled by people.",
    "population": "I2IDL types it as a Population.",
    "institutional-concept": "I2IDL types it as an Institutional Concept: educational organizations.",
    "policy": "I2IDL types it as a Policy.",
    "principle": "I2IDL types it as a Principle.",
    "discipline": "I2IDL types it as a Discipline: a field, used as a subject.",
    "field": "I2IDL types it as a Field of study, used as a subject.",
}

# concept id → (category, why). Every I2IDL "concept"-typed term is listed (that type has no default), plus the
# overrides of other types.
CONCEPT_CATEGORY = {
    # xAPI structures and identifiers: I2IDL defines them as representations, objects or values in xAPI data.
    "account-object": ("data", "Defined as an xAPI identity structure."),
    "activity-definition": ("data", "Defined as a metadata object inside an xAPI Activity."),
    "actor": ("data", "The Actor as represented in an xAPI Statement; xAPI's ontology makes Actor a part of Statement."),
    "anonymous-group": ("data", "An xAPI Group representation listed through its members."),
    "attachment": ("data", "A file or binary resource associated with a Statement."),
    "context-activities": ("data", "Activity references inside a Statement's Context."),
    "context-agent": ("data", "An xAPI context structure."),
    "context-group": ("data", "An xAPI context structure."),
    "context-object": ("data", "An optional xAPI Statement component."),
    "identified-group": ("data", "An xAPI Group representation with its own identifier."),
    "inverse-functional-identifier-ifi": ("data", "An identifier value."),
    "person-object": ("data", "An xAPI response object combining identifying information."),
    "registration": ("data", "An identifier for an instance of an Actor experiencing an Activity."),
    "result-object": ("data", "An optional xAPI Statement component holding a measured outcome."),
    "statement-reference": ("data", "An xAPI Object that refers to another Statement."),
    "subregistration": ("data", "An identifier extension distinguishing Patterns within a registration."),
    "substatement": ("data", "A Statement-like object embedded in another Statement."),
    "verb": ("data", "The xAPI element that identifies the action; the action itself is not what it names."),
    "xapi-agent": ("data", "Defined as an xAPI representation of an individual Actor."),
    "xapi-authority": ("data", "The authority element of a Statement."),
    "xapi-document": ("data", "Document data stored through xAPI resources."),
    "xapi-duration": ("data", "A duration value."),
    "xapi-extension": ("data", "A custom property in an xAPI extensions map."),
    "xapi-group": ("data", "Defined as an xAPI Actor representation for a collection of Agents."),
    "xapi-persona": ("data", "A set of identity representations."),
    "xapi-timestamp": ("data", "A time value."),
    "signed-statement": ("data", "An xAPI Statement carrying a signature (I2IDL types it as a Practice)."),
    "voided-statement": ("data", "A Statement marked invalid (I2IDL types it as a Practice)."),
    "statement-result": ("data", "A response structure returned by an LRS query (I2IDL types it as a System)."),
    "document-profile-resource": ("data", "A construct for storing name-and-document pairs (I2IDL types it as a System)."),
    "interaction-activity": ("data", "An xAPI Activity Definition (I2IDL types it as a Standard)."),
    "language-map": ("data", "An xAPI dictionary of language-tagged strings (I2IDL types it as a Standard)."),
    "xapi-statement": ("data", "The core xAPI data structure (I2IDL types it as a Standard)."),
    "activity": ("notion", "An xAPI Activity can be instruction, performance, an experience, a resource, an event or a physical object, so it has no single category."),
    # Data and records
    "administrative-data": ("data", "Data generated by administering an education system."),
    "data-silo": ("data", "An isolated store of data."),
    "digital-footprint": ("data", "Data produced through technology use."),
    "education-expenditure-data": ("data", "Financial data about education."),
    "enterprise-learner-record": ("data", "An organizational record of learner data (I2IDL types it as a System)."),
    "learner-model": ("data", "A representation of a learner's characteristics (I2IDL types it as a System)."),
    "learning-metadata": ("data", "Structured descriptive information."),
    "learning-record": ("data", "A machine-readable record of evidence about learning."),
    "named-graph": ("data", "An RDF graph that stores a Profile version."),
    "streaming-learning-data": ("data", "A continuous flow of activity and event data."),
    "survey-data": ("data", "Data collected through surveys and censuses."),
    "school-compliance-reporting": ("data", "Defined as the reports and forms provided to authorities (I2IDL types it as a Process)."),
    # Credentials
    "micro-credential": ("credential", "A credential for a smaller unit of learning."),
    "digital-credential": ("credential", "A digitally represented, verifiable claim (I2IDL types it as a System)."),
    "verifiable-learning-and-employment-record": ("credential", "A record whose claims others can verify (I2IDL types it as a System)."),
    # Information artifacts, models, norms, specifications, formats
    "controlled-vocabulary": ("information", "A managed set of defined terms."),
    "design-justification": ("information", "The recorded reason or evidence for a design decision."),
    "design-pattern": ("information", "A reusable description of a design problem and its solution."),
    "digital-global-public-goods": ("information", "Reusable digital resources: research, data, standards, algorithms and platforms."),
    "external-representation": ("information", "A concrete artifact that makes design thinking visible."),
    "prototype": ("information", "An early representation of a proposed solution."),
    "stakeholder-requirement": ("information", "A goal or requirement as a stakeholder expressed it."),
    "concept-map": ("information", "Defined as a representation of connected concepts (I2IDL types it as a Method)."),
    "persona": ("information", "Defined as a representation of a user type (I2IDL types it as a Method)."),
    "leed-tracker": ("information", "A documentation structure for design decisions (I2IDL types it as a System)."),
    "reflective-design-documentation": ("information", "Documentation used during design (I2IDL types it as a Practice)."),
    "connectivism": ("model", "A learning theory."),
    "social-constructivism": ("model", "A view of learning: a theory."),
    "yerkes-dodson-law": ("model", "A principle relating performance to arousal: a model."),
    "lifelong-learning": ("model", "A view of learning across the lifespan."),
    "future-learning-ecosystem": ("model", "A vision of learning as a connected continuum."),
    "samr-model": ("model", "A framework of four levels of technology use (I2IDL types it as a Method)."),
    "data-ownership": ("norm", "Rights, responsibilities and governance questions about data."),
    "ethics-of-ai": ("norm", "A body of ethical values, principles and rules for AI."),
    "human-accountability-in-ai": ("norm", "A principle that people remain responsible."),
    "social-responsibility-in-ai-education": ("norm", "A responsibility to consider AI's wider effects."),
    "data-privacy": ("norm", "Principles and practices that govern personal information (I2IDL types it as a Practice)."),
    "statement-immutability": ("norm", "An xAPI principle that stored Statements do not change (I2IDL types it as a Practice)."),
    "profile-version": ("specification", "An xAPI Profile as it exists at one point in time."),
    "rest-api": ("specification", "A web interface style: an architectural specification."),
    "statement-template": ("specification", "A set of rules for structuring Statements."),
    "statement-template-rule": ("specification", "A restriction within a Statement Template."),
    "xapi-pattern": ("specification", "A description of how Statements are grouped and ordered."),
    "total-learning-architecture-tla": ("specification", "A standards-based architecture for learning ecosystems (I2IDL types it as a System)."),
    "internationalized-resource-identifier-iri": ("format", "An identifier format."),
    "internationalized-resource-locator-irl": ("format", "An identifier format."),
    "json": ("format", "A text format for structured data."),
    "json-ld": ("format", "A JSON-based linked-data format."),
    "resource-description-framework-rdf": ("format", "A data model and its serializations."),
    "sparql": ("format", "A query language."),
    "simple-knowledge-organization-system-skos": ("format", "A W3C vocabulary for concept schemes: a data language."),
    "shareable-competency-definition-scd": ("format", "A machine-readable format for competency definitions."),
    # Plans: methods and programmes
    "artificial-intelligence-ai": ("method", "A broad class of computational techniques."),
    "asset-model": ("method", "An approach that starts from learners' strengths."),
    "human-centered-education": ("method", "An approach to education."),
    "linked-data": ("method", "A way of publishing and connecting data."),
    "whole-person-development": ("method", "An approach to development."),
    "privacy-by-design": ("method", "An approach to building privacy into systems (I2IDL types it as a Practice)."),
    "ethics-by-design": ("method", "An approach to building ethical requirements into AI systems (I2IDL types it as a Practice)."),
    "human-centred-approach-to-ai": ("method", "An approach to AI (I2IDL types it as a Practice)."),
    "multi-stakeholder-approach": ("method", "An approach to designing education technology (I2IDL types it as a Practice)."),
    "whole-of-government-approach": ("method", "An approach to coordinating government (I2IDL types it as a Practice)."),
    "agile-development": ("method", "An iterative approach to creating solutions (I2IDL types it as a Practice)."),
    "lean-agile": ("method", "A family of approaches (I2IDL types it as a Practice)."),
    "iterative-design": ("method", "A design approach (I2IDL types it as a Practice)."),
    "competency-based-learning": ("method", "An approach that organizes progress around mastery (I2IDL types it as a Practice)."),
    "mastery-learning": ("method", "An instructional approach (I2IDL types it as a Practice)."),
    "flipped-classroom": ("method", "An instructional approach (I2IDL types it as a Practice)."),
    "systems-thinking": ("method", "An approach to understanding problems (I2IDL types it as a Practice)."),
    "human-systems-integration-hsi": ("method", "A philosophy and set of processes (I2IDL types it as a Practice)."),
    "xapi-concurrency-control": ("method", "A technique using HTTP entity tags (I2IDL types it as a Practice)."),
    "user-tailored-privacy": ("method", "A privacy approach (I2IDL types it as a System)."),
    "connectivist-mooc-cmooc": ("program", "A kind of online course."),
    "extended-mooc-xmooc": ("program", "A kind of online course."),
    "early-childhood-education-ece": ("program", "ISCED level 0 programmes."),
    "early-childhood-education-and-care-ecec": ("program", "Services and programmes for young children."),
    "unesco-curriculum": ("program", "The planned subjects and content of an educational programme."),
    "massive-open-online-course-mooc": ("program", "An online course (I2IDL types it as a System)."),
    # Things that happen
    "assessment": ("assessment", "The collection and interpretation of evidence about learning."),
    "fairness": ("assessment", "Defined as the evaluation of whether people are treated appropriately."),
    "formative-assessment": ("assessment", "Assessment used during learning (I2IDL types it as a Practice)."),
    "summative-assessment": ("assessment", "Assessment at the end of a period (I2IDL types it as a Practice)."),
    "ai-tool-validation-for-education": ("assessment", "The systematic evaluation of an AI tool (I2IDL types it as a Practice)."),
    "review-and-monitoring": ("assessment", "Systematic examination against plans and indicators (I2IDL types it as a Practice)."),
    "a-b-testing": ("assessment", "A controlled comparison (I2IDL types it as a Method)."),
    "accessibility-and-inclusivity-testing": ("assessment", "Testing whether a solution is usable by everyone (I2IDL types it as a Method)."),
    "cognitive-walkthrough": ("assessment", "A usability inspection (I2IDL types it as a Method)."),
    "cross-national-assessment": ("assessment", "An international learning assessment (I2IDL types it as a Method)."),
    "learning-assessment": ("assessment", "A structured process for measuring knowledge and skills (I2IDL types it as a Method)."),
    "testing-for-learning-impact": ("assessment", "Evaluation of whether a solution changes learning (I2IDL types it as a Method)."),
    "usability-testing": ("assessment", "Evaluation with representative users (I2IDL types it as a Method)."),
    "user-testing": ("assessment", "Direct evaluation with users (I2IDL types it as a Method)."),
    "pattern-validation": ("assessment", "Validating Statements against a Pattern (I2IDL types it as a Process)."),
    "statement-template-validation": ("assessment", "Validating a Statement against templates (I2IDL types it as a Process)."),
    "asynchronous-learning": ("learning", "Learning activity at different times."),
    "computer-based-learning": ("learning", "Training or education through computers."),
    "distributed-learning": ("learning", "Learning delivered beyond one classroom."),
    "experiential-learning": ("learning", "Learning through experience and reflection."),
    "meaningful-learning": ("learning", "Learning with intentional, active engagement."),
    "mobile-learning": ("learning", "Learning through mobile devices."),
    "multimedia-learning": ("learning", "Learning with more than one mode of presentation."),
    "observational-learning": ("learning", "Learning by observing others."),
    "online-learning-modality": ("learning", "A mode of online learning; it classifies learning activities."),
    "personalized-learning": ("learning", "Learning designed around an individual."),
    "remote-learning": ("learning", "Learning at a distance."),
    "resource-facilitated-learning": ("learning", "Learning guided mainly by resources."),
    "self-regulated-learning": ("learning", "Learning that the learner plans and regulates."),
    "social-learning": ("learning", "Learning through interaction with others."),
    "synchronous-learning": ("learning", "Learning activity in real time."),
    "ubiquitous-learning": ("learning", "Learning across places, times and devices."),
    "unesco-education-domain": ("learning", "The process through which people develop abilities, attitudes and knowledge."),
    "microlearning": ("learning", "Learning in small units (I2IDL types it as a Practice)."),
    "multi-channel-remote-learning": ("learning", "Remote learning through several channels (I2IDL types it as a Practice)."),
    "ai-for-professional-development": ("learning", "Teachers' professional learning with AI (I2IDL types it as a Practice)."),
    "instructor-facilitated-learning": ("teaching", "Learning an instructor actively guides."),
    "mentorship": ("teaching", "A more experienced person models skills for a learner (I2IDL types it as a Practice)."),
    "ai-assisted-teaching": ("teaching", "Teaching with AI tools (I2IDL types it as a Practice)."),
    "unesco-teaching-and-training": ("teaching", "Organized methods and processes that facilitate learning through instruction (I2IDL types it as a Practice)."),
    "design-decision": ("activity", "A choice made about a learning design."),
    "digital-security": ("activity", "Defined as the protection of digital systems and data."),
    "education-technology-edtech": ("activity", "Defined as the use of technology in education."),
    "empathy": ("activity", "Defined as the effort to understand users' needs."),
    "learner-privacy": ("activity", "Defined as the protection and management of privacy interests."),
    "open-standards-and-architecture-for-interoperability": ("activity", "Defined as the use of open standards."),
    "security": ("activity", "Defined as the protection of systems and data."),
    "decision-support": ("activity", "Defined as the use of data and tools to help people decide (I2IDL types it as a System)."),
    "distributed-simulation": ("activity", "Simulation conducted across networked systems (I2IDL types it as a System)."),
    "data-analytics": ("activity", "Defined as the use of methods to examine data (I2IDL types it as a Method)."),
    "data-mining": ("activity", "Defined as the use of computational methods (I2IDL types it as a Method)."),
    "exploratory-research": ("activity", "Research activity (I2IDL types it as a Method)."),
    "inference-modeling": ("activity", "Defined as the use of models to infer (I2IDL types it as a Method)."),
    "modeling-and-simulation": ("activity", "Defined as the use of representations to explore systems (I2IDL types it as a Method)."),
    "predictive-modeling": ("activity", "Defined as the use of models to estimate outcomes (I2IDL types it as a Method)."),
    "attention": ("process", "The selective allocation of cognitive resources: a mental process."),
    "building-expertise": ("process", "The development of knowledge and skill over time."),
    "design-judgment": ("process", "The reasoning behind a design choice."),
    "education-data-cycle": ("process", "A recurring sequence of producing and using data."),
    "feedback-loop": ("process", "A cycle in which information about outcomes is returned."),
    "learner-feedback-loop": ("process", "A feedback cycle about learner activity."),
    "learning-event": ("process", "A discrete occurrence in a learning experience."),
    "learning-experience": ("process", "An event associated with learning."),
    "meta-adaptation": ("process", "Adaptation across learning systems."),
    "motivation": ("process", "Defined as the processes that influence whether a learner initiates and persists."),
    "personalization": ("process", "The adjustment of learning to an individual, by people or systems."),
    "sensemaking": ("process", "A social and cognitive process of interpretation."),
    "metacognitive-monitoring": ("process", "A mental process of observing one's own understanding (I2IDL types it as a Practice)."),
    "self-monitoring": ("process", "A learner's ongoing observation of their own learning (I2IDL types it as a Practice)."),
    # Characteristics
    "ai-explainability-in-education": ("quality", "The extent to which educators can understand an AI system."),
    "bias": ("quality", "A systematic distortion in data, models or decisions."),
    "cognitive-engagement": ("quality", "The degree to which a learner actively thinks."),
    "cognitive-load": ("quality", "The mental effort a task requires."),
    "data-availability": ("quality", "The condition of data existing and being accessible."),
    "data-quality": ("quality", "The degree to which data is fit for use."),
    "educational-attainment": ("quality", "The highest level of education a person has completed."),
    "equity": ("quality", "Whether opportunities and outcomes fairly account for different needs: a property of them."),
    "extraneous-cognitive-load": ("quality", "Mental effort caused by presentation."),
    "flow": ("quality", "A state of deep engagement."),
    "learner-variability": ("quality", "Differences among learners."),
    "operational-feasibility": ("quality", "The degree to which a solution can be implemented and sustained."),
    "standards-compliance": ("quality", "The degree of conformance to a standard."),
    "technology-constraint": ("quality", "A limit of a technology."),
    "profile-based-statement-conformance": ("quality", "Conformance of Statements to a Profile (I2IDL types it as a Practice)."),
    "education-statistical-capacity": ("disposition", "The capability of an education system to produce and use data."),
    "human-agency-in-ai": ("disposition", "The capacity of people to retain control."),
    "interoperability": ("disposition", "The ability of systems to work together."),
    "knowledge-retention": ("disposition", "The persistence of learned knowledge."),
    "learner-agency": ("disposition", "The capacity of learners to make choices."),
    "long-term-memory": ("disposition", "A memory system: a cognitive capacity."),
    "scalability": ("disposition", "The ability to handle growth."),
    "semantic-interoperability": ("disposition", "The ability to exchange data with shared meaning."),
    "short-term-memory": ("disposition", "A cognitive capacity."),
    "technology-affordance": ("disposition", "A capability of a technology."),
    "working-memory": ("disposition", "A limited-capacity memory system: a cognitive capacity."),
    "user-directed-customization": ("disposition", "The ability for users to adapt a technology (I2IDL types it as a Practice)."),
    "ai-foundations-and-applications": ("competence", "Conceptual knowledge and operational skills."),
    "ai-literacy-for-teachers": ("competence", "A set of AI competencies."),
    "competency": ("competence", "A capability, skill or knowledge area. Its formal description is information, which CTDL-ASN, CASE and IEEE LER publish."),
    "conceptual-knowledge": ("competence", "Knowledge of ideas and relationships."),
    "digital-literacies": ("competence", "Capabilities for using digital technologies."),
    "digital-skills": ("competence", "Skills for using digital technologies."),
    "metacognition": ("competence", "Awareness and regulation of one's own thinking."),
    "practitioner-expertise": ("competence", "Knowledge and judgement from practice."),
    "prior-knowledge": ("competence", "Knowledge a learner already has."),
    "procedural-knowledge": ("competence", "Knowledge of how to carry out a procedure."),
    "growth-mindset": ("attitude", "A belief that abilities can develop."),
    "human-centred-mindset": ("attitude", "A values- and attitudes-based orientation."),
    "interdisciplinary-research-identity": ("attitude", "A professional self-understanding."),
    "locus-of-control": ("attitude", "A belief about what influences outcomes."),
    "productive-mindset": ("attitude", "A pattern of beliefs and attitudes."),
    "self-efficacy": ("attitude", "A belief in one's own capability."),
    "full-time-equivalent-teacher-fte": ("measure", "A standardised measure of teacher workload."),
    "learning-poverty": ("measure", "A measure of the share of children who cannot read a simple story."),
    "minimum-proficiency-level": ("measure", "A benchmark."),
    "national-sdg-4-benchmark": ("measure", "A quantitative reference point."),
    "total-cost-of-ownership-tco": ("measure", "A cost over a lifecycle."),
    "childcare-gap": ("situation", "A period without entitled childcare: a condition families are in."),
    "contextual-factor": ("situation", "A condition surrounding a design."),
    "contextually-rich-learning-environment": ("situation", "A learning environment understood in its setting."),
    "data-culture": ("situation", "An organizational environment."),
    "digital-divide": ("situation", "Inequality in access and skills."),
    "learning-environment": ("situation", "The combined conditions in which learning occurs."),
    "problem-space": ("situation", "The contextual setting of a learning challenge."),
    "vendor-lock-in": ("situation", "A condition in which earlier choices constrain later ones."),
    # Agents and groups
    "metadata-consumer": ("agent", "A person, organization or program that resolves IRIs."),
    "metadata-provider": ("agent", "A person, organization or program that creates IRIs."),
    "profile-author": ("agent", "A person or group writing an xAPI Profile (a Role in I2IDL, possibly a group)."),
    "profile-validator": ("agent", "A person or machine that validates xAPI data (a Role in I2IDL, possibly software)."),
    "xapi-client": ("agent", "Any entity that interacts with xAPI services (I2IDL types it as a System)."),
    "instructional-designer": ("person", "A professional (I2IDL types it as a Discipline)."),
    "learning-design-practitioner": ("person", "An umbrella term for practitioners (I2IDL types it as a Discipline)."),
    "learning-engineer": ("person", "A professional (I2IDL types it as a Discipline)."),
    "subject-matter-expert-sme": ("person", "A person with deep domain knowledge (I2IDL types it as a Discipline)."),
    "learning-organization": ("organization", "An organization that learns from evidence."),
    "ieee-learning-technology-standards-committee-ltsc": ("organization", "A standards committee (I2IDL types it as a Standard)."),
    "community-of-practice": ("group", "A community of people in a shared practice."),
    "edtech-ecosystem": ("group", "Defined as the network of stakeholders in education technology."),
    "learning-community": ("group", "A group of learners."),
    "learning-engineering-team": ("group", "The person or group assembled for a learning challenge."),
    "learning-network": ("group", "A network of relationships among learners, teachers and communities."),
    "networked-community": ("group", "A connected community of researchers and practitioners."),
    "coordination-network": ("group", "A network connecting participants (I2IDL types it as a System)."),
    # Systems and things
    "about-resource": ("webapi", "The xAPI /about resource (I2IDL types it as a System)."),
    "activity-profile-resource": ("webapi", "The xAPI /activities/profile resource (I2IDL types it as a System)."),
    "agent-profile-resource": ("webapi", "The xAPI /agents/profile resource (I2IDL types it as a System)."),
    "state-resource": ("webapi", "The xAPI /activities/state resource (I2IDL types it as a System)."),
    "statement-resource": ("webapi", "The LRS /statements resource (I2IDL types it as a System)."),
    "endpoint": ("webapi", "An entry point for communicating with a service (I2IDL types it as a System)."),
    "data-pipeline": ("software", "A sequence of processes moving data, implemented in software (I2IDL types it as a System)."),
    "system-of-systems": ("ecosystem", "A capability formed by interacting systems."),
    "education-data-ecosystem": ("ecosystem", "Data sources, processes, institutions and uses together (I2IDL types it as a System)."),
    "human-support-system": ("ecosystem", "People, roles, practices and structures that support learners (I2IDL types it as a System)."),
    "unesco-educational-systems-and-levels": ("ecosystem", "The organized structures through which education is provided (I2IDL types it as a System)."),
    "instrumentation": ("technology", "Sensors, software, schemas and processes used to observe a system."),
    "mixed-reality": ("technology", "A continuum of immersive technologies."),
    "trustworthy-ai-for-education": ("technology", "AI systems used in education with certain properties."),
    "sensor": ("technology", "A hardware or software mechanism (I2IDL types it as a System)."),
    "digital-learning-materials": ("resource", "Digital content and resources for learning."),
    "open-educational-resources-oer": ("resource", "Openly licensed learning resources."),
    "worked-example": ("resource", "A step-by-step demonstration for learners (I2IDL types it as a Method)."),
    "simulation": ("resource", "A representation used for practice and experimentation (I2IDL types it as a System)."),
    # Subjects
    "control-theory": ("discipline", "An engineering field."),
    "pedagogy": ("discipline", "The theory and practice of teaching."),
    "source-of-influence": ("notion", "A factor of any kind — data, research, experience, technology — cited for a decision."),
    "emergent-impact": ("notion", "Effects, uses, outcomes or extensions of any kind."),
}

# ── What I2IDL's own records are (record alignments) ──────────────────────────────────────────────────
# Subjects are I2IDL-X classes (or the I2IDL classes I2IDL-X already declares, gs:). Each row: subject, targets, why.
RECORDS = [
    ("i2x:GlossaryConcept", ["obo:IAO_0000030", "cco:ont00000958", "gist:KnowledgeConcept", "dul:Concept"],
     "An I2IDL concept is a term: an information content entity about what it classifies (IAO, CCO), a DUL Concept, and a gist KnowledgeConcept — richer than a gist Category because it carries a definition, evidence and relations. It is already a schema.org DefinedTerm."),
    ("gs:Definition", ["obo:IAO_0000300", "cco:ont00000853", "gist:Text", "dul:InformationObject"],
     "A definition record is text that describes its concept: IAO textual entity, CCO Descriptive ICE, gist Text, a DUL information object."),
    ("gs:Evidence", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject"],
     "An evidence record cites a source for a definition: information content."),
    ("i2x:GlossarySource", ["obo:IAO_0000310", "cco:ont00002039", "gist:Content", "dul:InformationObject", "schema:CreativeWork"],
     "A source I2IDL cites is a document."),
    ("i2x:GlossaryCollection", ["obo:IAO_0000030", "gist:Collection", "dul:Collection", "schema:DefinedTermSet"],
     "An I2IDL collection groups concepts: a DUL and gist Collection and a schema.org DefinedTermSet."),
    ("i2x:GlossaryRelease", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject", "schema:Dataset"],
     "A release is a published version of the glossary dataset."),
    ("i2x:ReleaseChange", ["obo:BFO_0000015", "cco:ont00000005", "gist:Event", "dul:Action", "gufo:Event", "schema:UpdateAction"],
     "The editing between two releases: a process in which editors act, an UpdateAction in schema.org."),
    ("i2x:ChangeEvent", ["obo:BFO_0000015", "gist:Event", "dul:Event", "gufo:Event"],
     "One kind of change within a release change: part of that process."),
    ("i2x:Enactment", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject"],
     "A reified concept-to-capability link, held as a record."),
    ("i2x:MappingProposal", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject"],
     "A proposed crosswalk, held as a record."),
    ("i2x:RatificationVote", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject"],
     "The record of a vote; the voting itself is an act."),
    ("i2x:UsageRecord", ["obo:IAO_0000027", "gist:Content", "dul:InformationObject"],
     "The RDF projection of an xAPI statement: data."),
    ("i2x:CourseConceptAlignment", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject"],
     "A proposed alignment, held as a record."),
    ("i2x:StoredQuery", ["obo:IAO_0000010", "gist:Content", "dul:InformationObject"],
     "A parameterized SPARQL query: instructions a query engine executes."),
    ("i2x:ServiceLimits", ["obo:IAO_0000033", "gist:Specification", "dul:Description"],
     "Published operating limits that prescribe how clients may use a service."),
    ("i2x:GlossaryCatalog", ["obo:IAO_0000310", "gist:Content", "dul:InformationObject", "schema:DataCatalog"],
     "The agent catalog is a document that catalogs data services."),
    ("i2x:TemplatedAffordance", ["obo:IAO_0000007", "cco:ont00000965", "gist:ServiceSpecification", "dul:Description"],
     "A templated control describes an action an agent can take: an IAO action specification, a gist ServiceSpecification."),
    ("i2x:ActionIdentity", ["obo:IAO_0000030", "cco:ont00000686"],
     "An action IRI designates an action: a CCO Designative ICE."),
]
# Individuals I2IDL-X types (rdf:type) or classifies (i2x:isClassifiedBy) — the glossary classifying the very
# services that publish it.
INDIVIDUALS = [
    ("https://id.i2idl.org/scheme", ["gist:ControlledVocabulary", "schema:DefinedTermSet", "dul:Description", "obo:IAO_0000310"],
     ["controlled-vocabulary"], "I2IDL's concept scheme is a controlled vocabulary — and I2IDL's own concept 'Controlled vocabulary' classifies it."),
    ("https://id.i2idl.org/sparql", [], ["endpoint"], "I2IDL's SPARQL service is an endpoint, in I2IDL's own sense."),
    ("https://foxxi-bridge.interego.xwisee.com/xapi/profile", [], ["xapi-profile"], "Foxxi's published xAPI profile is an xAPI Profile."),
]

# ── Interego and Foxxi, aligned to the same upper ontologies ──────────────────────────────────────────
INTEREGO = [
    ("iep:ContextDescriptor", ["obo:IAO_0000027", "cco:ont00000853", "gist:Content", "dul:InformationObject", "dcat:CatalogRecord"],
     "A descriptor makes claims about a graph (provenance, modal status, trust): descriptive data, a DCAT catalog record."),
    ("iep:Affordance", ["obo:IAO_0000007", "cco:ont00000965", "gist:ServiceSpecification", "dul:Description"],
     "An affordance describes an action an agent can take: an IAO action specification and gist ServiceSpecification."),
    ("iep:AffordanceManifest", ["obo:IAO_0000310", "gist:Content", "dul:InformationObject"], "A manifest is a document of affordances."),
    ("iep:Ratifiable", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject"], "A ratifiable proposal is information awaiting votes."),
    ("ie:Act", ["obo:BFO_0000015", "cco:ont00000402", "gist:Event", "dul:Action", "gufo:Event", "schema:AskAction"],
     "Posing an interrogative: a CCO Act of Communication, a schema.org AskAction."),
    ("ie:Response", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject", "schema:Answer"], "Content offered in response: an answer."),
    ("ie:Sign", ["dul:InformationEntity"], "Peircean signs include gestures and data patterns, so only DUL's catch-all InformationEntity fits all of them."),
    ("ie:Interpretant", ["dul:Description"], "The meaning an agent derives from a sign: a conceptualization (DUL Description)."),
    ("hyprcat:FederatedCatalog", ["obo:IAO_0000310", "gist:Content", "dul:InformationObject", "schema:DataCatalog"], "A federated DCAT catalog."),
    ("hyprcat:FederatedDataProduct", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject", "schema:Dataset"], "A data product: a dataset with ports."),
    ("hyprcat:PortAffordance", ["obo:IAO_0000007", "gist:ServiceSpecification"], "An input or output port: an action specification."),
    ("hypragent:Agent", ["dul:Agent"], "A software agent with a DID; PROV already types it as a software agent."),
    ("hypragent:Principal", ["obo:BFO_0000040", "cco:ont00001017", "dul:Agent", "prov:Agent"],
     "The human or organization an agent acts for: a material agent in BFO/CCO."),
    ("hypragent:Capability", ["obo:IAO_0000007", "gist:ServiceSpecification", "dul:Description"],
     "A registered capability describes what an agent can do."),
    ("hypragent:Dispatch", ["obo:BFO_0000015", "gist:Event", "dul:Action", "gufo:Event", "schema:Action"], "One recorded invocation: an action."),
    ("hypragent:DelegationChain", ["obo:IAO_0000310", "cco:ont00002002", "gist:Content", "dul:InformationObject"],
     "Verifiable credentials that prove delegated authority: a CCO Certificate."),
    ("ieh:AgentMemory", ["obo:IAO_0000027", "gist:Content", "dul:InformationObject"], "A memory entry: data."),
    ("ieh:AgentAction", ["obo:BFO_0000015", "gist:Event", "dul:Action", "gufo:Event", "schema:Action"], "A tool call an agent made."),
    ("ieh:AgentTurn", ["obo:BFO_0000015", "gist:Event", "dul:Action", "gufo:Event"], "One model invocation."),
    ("ieh:Decision", ["obo:BFO_0000015", "gist:Determination", "dul:Action", "gufo:Event"], "Resolving an affordance with a justification: a gist Determination."),
    ("ieh:PolicyRule", ["obo:IAO_0000033", "cco:ont00000965", "gist:Requirement", "dul:Norm"], "A deontic rule: prescriptive information, a DUL Norm."),
    ("ieh:AffordanceDecorator", ["obo:IAO_0000010", "gist:Component", "dul:InformationObject"], "A pluggable component: software."),
    ("ieh:Protocol", ["obo:IAO_0000033", "gist:Specification", "dul:Description"], "An attested set of affordances that prescribes how agents interact."),
    ("ieh:WorkflowApp", ["obo:IAO_0000104", "gist:TaskTemplate", "dul:Workflow"], "An ordered composition of affordances: a DUL Workflow."),
]
FOXXI = [
    ("ler:Credential", ["obo:IAO_0000310", "cco:ont00002002", "gist:Content", "dul:InformationObject", "schema:EducationalOccupationalCredential"],
     "A signed attestation of qualification: a CCO Certificate.", ["ob3:OpenBadgeCredential", "elm:EuropeanDigitalCredential"]),
    ("ler:CompetencyDefinition", ["obo:IAO_0000030", "cco:ont00000853", "gist:Content", "dul:InformationObject"],
     "A representation of one competency: information about a capability, not the capability.", ["ceasn:Competency", "case:dtCFItem", "asn:Statement", "tla:Competency"]),
    ("ler:CompetencyFramework", ["obo:IAO_0000310", "gist:Content", "dul:InformationObject"],
     "A structured collection of competency definitions.", ["ceasn:CompetencyFramework", "case:dtCFDocument", "asn:StandardDocument", "tla:CompetencyFramework"]),
    ("ler:CompetencyAssertion", ["obo:IAO_0000027", "gist:Content", "dul:InformationObject"], "A claim that a learner can perform a competency: data.", ["tla:Assertion"]),
    ("ler:Transcript", ["obo:IAO_0000310", "cco:ont00002002", "gist:Content", "dul:InformationObject"], "A learner's academic record.", []),
    ("ler:Rubric", ["obo:IAO_0000033", "gist:Specification", "dul:Description"], "Evaluation criteria.", ["asn:Rubric", "case:dtCFRubric"]),
    ("ler:Learner", ["obo:BFO_0000030", "cco:ont00001262", "gist:Person", "dul:Person"], "The natural person a record is about.", []),
    ("ler:Issuer", ["dul:Agent"], "An authority that confers credentials (a role of an agent).", []),
    ("ler:Evidence", ["obo:IAO_0000030", "gist:Content", "dul:InformationObject"], "Anything presented in support of an assertion, as a record.", []),
    ("ler:LearnerProfile", ["obo:IAO_0000027", "gist:Content", "dul:InformationObject"], "A per-learner container of data.", ["tla:LearnerProfile"]),
    ("tla:Competency", ["obo:IAO_0000030", "cco:ont00000853", "gist:Content", "dul:InformationObject"],
     "A competency node in a framework: information about a capability.", ["ceasn:Competency", "case:dtCFItem"]),
    ("tla:CompetencyFramework", ["obo:IAO_0000310", "gist:Content", "dul:InformationObject"], "A graph of competencies.", ["ceasn:CompetencyFramework", "case:dtCFDocument"]),
    ("tla:LearnerProfile", ["obo:IAO_0000027", "gist:Content", "dul:InformationObject"], "Each learner's aggregate data.", []),
    ("tla:LearningActivityMetadata", ["obo:IAO_0000027", "gist:Content", "dul:InformationObject"], "A metadata descriptor of a learning resource.", []),
    ("tla:CompetencyManagementService", ["obo:IAO_0000010", "gist:System", "dul:InformationObject", "schema:WebAPI"], "A service.", []),
    ("tla:LearningEventManager", ["obo:IAO_0000010", "gist:System", "dul:InformationObject", "schema:WebAPI"], "A service.", []),
    ("tla:MoveOnRule", ["obo:IAO_0000033", "gist:Requirement", "dul:Norm"], "A completion criterion.", []),
    ("tla:RollupRule", ["obo:IAO_0000033", "gist:Requirement", "dul:Norm"], "A derivation rule.", []),
]

# I2IDL-X properties aligned to the upper ontologies' classification and aboutness relations.
PROPERTIES = [
    ("i2x:isClassifiedBy", "rdfs:subPropertyOf", "dul:isClassifiedBy",
     "DUL's classification relation (Entity → Concept); I2IDL-X's is narrower: the concept is an I2IDL concept and the relation is instance-of."),
    ("i2x:isClassifiedBy", "rdfs:subPropertyOf", "gist:isCategorizedBy", "gist's categorization relation."),
    ("i2x:classifies", "rdfs:subPropertyOf", "obo:IAO_0000136", "IAO 'is about': an information content entity is about what it classifies."),
    ("i2x:aboutConcept", "rdfs:subPropertyOf", "obo:IAO_0000136", "A usage record is about the concept it tags."),
    ("i2x:aboutConcept", "rdfs:subPropertyOf", "gist:isAbout", "gist's aboutness relation (domain gist:Content)."),
]
